[FEAT]: Integrate Openai API in our backend
hrachocode/hydralab pull request #205
Opened 2023-01-23 09:50 UTC by tumero58

2023-01-23 12:32 UTC, hrachocode requested changes
I guess file name should be api/createPost for better understanding

2023-01-23 12:32 UTC, hrachocode commented on constants/openai.ts
> +export const OPEN_AI_PROMPT_KEY: string = "open-ai-prompt";
these 2 are static constants?

2023-01-23 14:40 UTC, tumero58 commented
[OpenAI research](https://docs.google.com/document/d/e/2PACX-1vRvYYSViAQCBClNlEOvZ889kA7XiAodPQoBAfh_dPFKnfgo13XfqOnMA0MXEA0ucqsrH-MZG3Zg0Xno/pub)

2023-01-25 09:13 UTC, hrachocode requested changes

2023-01-25 09:13 UTC, hrachocode commented on constants/openai.ts
> +export const OPEN_AI_IMAGE_SIZE: string = "1024x1024";
does this size fits with the size in design?

2023-01-25 09:13 UTC, hrachocode commented on utils/openai/generatePost.ts
> +  return { textResult, imageResult };
imageResult is a link or is a binary representation of the image?

2023-01-25 09:16 UTC, tumero58 commented on constants/openai.ts
> +export const OPEN_AI_IMAGE_SIZE: string = "1024x1024";
it is higher so it won't hurt the quality

2023-01-25 09:17 UTC, tumero58 commented on utils/openai/generatePost.ts
> +  return { textResult, imageResult };
it is an object with a image link inside

2023-01-25 10:14 UTC, hrachocode approved these changes

2023-01-25 11:18 UTC, merged