[FEAT]: Remote post CMS
hrachocode/hydralab pull request #206
Opened 2023-01-26 14:30 UTC by tumero58

2023-01-26 14:48 UTC, hrachocode requested changes

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +  const result:{data:{token: string}} = await httpClient.post(`${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_BASE_ROUTE}${CMS_API_JWT}`, {
```suggestion
  const { data: { token = '' } = {} } : { data: { token: string } } = await httpClient.post(`${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_BASE_ROUTE}${CMS_API_JWT}`, {
```

I guess we need to config linter to put spaces

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +  if (result.data.token){
```suggestion
  if (token){
```

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +    localStorage.setItem(JWT, result.data.token);
```suggestion
    localStorage.setItem(JWT, token);
```

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +const createPost = async (CMS_URL:string, body: object, isDraft:boolean | undefined) => {
```suggestion
const createPost = async (CMS_URL: string, body: object, isDraft:boolean | undefined) => {
```

I guess we need some typescript eslint plugin or maybe couple TS rules

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +    status: isDraft ? STATUS_DRAFT : STATUS_PUBLISH
we can publish draft articles from there?

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +  await httpClient.post(`${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_BASE_ROUTE}${CMS_API_VERSION}/${CMS_URL}`, {
lets put this inside try/catch, so runtime will be safe running

2023-01-26 14:48 UTC, hrachocode commented on utils/CMSApi/remotePublish.ts
> +    if ((error as IError).status === StatusCode.Forbidden || (error as IError).status === StatusCode.Unauthorized){
we dont need to handle it here. here we can simply throw an error, it will be handle on httpCleint.ts error switch/case file, where we can check if its regarding the posts, and put some logic there

2023-01-26 14:55 UTC, tumero58 commented on utils/CMSApi/remotePublish.ts
> +  await httpClient.post(`${process.env.NEXT_PUBLIC_BASE_URL}${process.env.NEXT_PUBLIC_BASE_ROUTE}${CMS_API_VERSION}/${CMS_URL}`, {
safety is checked before running this function.

2023-01-27 13:02 UTC, hrachocode requested changes

2023-01-27 13:02 UTC, hrachocode commented on utils/CMSApi/remotePostRequest.ts
> +export const remotePostRequest =  async (CMS_URL: string, body:object, isDraft?:boolean) => {
we dont need this function no more as the forbidden or unauthroized case will ba handle on httpClient

2023-01-27 13:02 UTC, hrachocode commented on utils/CMSApi/remotePostRequest.ts
> +export const remotePostRequest =  async (CMS_URL: string, body:object, isDraft?:boolean) => {
we can directly use postToCms(renamed to CMSPostRequestHandler function only)

2023-01-27 13:02 UTC, hrachocode commented on configs/api/httpClient/HttpClient.ts
> +          this.instance?.request(originalRequest);
have we checked if this implementation is working as expected? I mean if we have originalRequest object when we will use this with postman ?

2023-01-27 13:22 UTC, hrachocode approved these changes

2023-01-27 13:26 UTC, merged