services, portfolio, case-study pages
hrachocode/hydralab pull request #50
Opened 2022-09-09 10:02 UTC by rafonersisyan

pages/case-study/index.tsx
commented code in this file must stay (don't review this file)

2022-09-09 21:45 UTC, hrachocode requested changes

2022-09-09 21:45 UTC, hrachocode commented on pages/blog/[id].tsx
> +      setTags(tags.map((item: any) => item.name));
```suggestion
      setTags(tags.map((item: types) => item.name));
```

2022-09-09 21:45 UTC, hrachocode commented on pages/blog/[id].tsx
> +      const { data: tags } = await httpClient.get(`http://localhost/hydralab/wp-json/wp/v2/tags?post=${id}`);
```suggestion
      const { data: tags } = await httpClient.get(`http://localhost/hydralab/wp-json/wp/v2/tags?post=${id}`);
```

this localhost should be replaced with localhost:PORT after latest Karen changes, and should be placed in environment variable

2022-09-09 21:45 UTC, hrachocode commented on pages/case-study/[id].tsx
> +    const fetchData = async () => {
```suggestion
    const fetchData = async () => {
```

I think we can create general reusable fetchData function

2022-09-09 21:45 UTC, hrachocode commented on pages/case-study/index.tsx
> +// import { BlogCategories } from "../components/blogPage/categories/BlogCategories";
please remove all unused comments from code

2022-09-09 21:45 UTC, hrachocode commented on pages/components/caseStudyInnerPage/CaseStudyInnerPage.tsx
> +export const CaseStudyPage = ({ caseStudy }: any) => {
```suggestion
export const CaseStudyPage = ({ caseStudy }: types) => {
```

2022-09-09 21:45 UTC, hrachocode commented on pages/components/homePage/shortAboutUs/ShortAboutUs.tsx
> +          onClick={()=> {window.scrollTo({ top: 1750, behavior: "smooth" });}}
```suggestion
          onClick={()=> {window.scrollTo({ top: DYNAMIC, behavior: "smooth" });}}
```

fixed 1750 will broke in other screens

2022-09-09 21:45 UTC, hrachocode commented on pages/components/joinUsPage/buildYourCareer/BuildYourCareer.tsx
> +    const elem = document.getElementById("apply-for-job");
```suggestion
    const elem = document.getElementById(APPLY_SECTION_ID);
```

2022-09-09 21:45 UTC, hrachocode commented on pages/components/joinUsPage/buildYourCareer/BuildYourCareer.tsx
> +      const height = elem.getBoundingClientRect().top + document.documentElement.scrollTop - 80;
```suggestion
      const height = elem.getBoundingClientRect().top + document.documentElement.scrollTop - DYNAMIC;
```

80 will also gets broken if header will change its sizes

2022-09-09 21:45 UTC, hrachocode commented on pages/components/portfolioInnerPage/PortfolioInnerPage.tsx
> +export const PortfolioInnerPage = ({ product }: any) => {
```suggestion
export const PortfolioInnerPage = ({ product }: types) => {
```

2022-09-09 21:45 UTC, hrachocode commented on pages/components/portfolioPage/portfolioExamples/PortfolioExamples.tsx
> +        {products.map((item: any, index: number) => {
```suggestion
        {products.map((item: types, index: number) => {
```

2022-09-09 21:45 UTC, hrachocode commented on pages/components/shared/Spinner.tsx
> +            <Skeleton sx={{ width: "100%", height: "10vh", margin: 0 }}/>
does this skeleton will work in case of mobile view?

2022-09-09 21:45 UTC, hrachocode commented on pages/components/shared/Spinner.tsx
> +            <Skeleton sx={{ width: "100%", height: "30vh", margin: 0 }}/>
```suggestion
            <Skeleton sx={{ width: "100%", height: "30vh", margin: 0 }}/>
```

does 30HV makes it dynamic ?

2022-09-09 21:45 UTC, hrachocode commented on pages/components/workWithUs/WorkWithUs.tsx
> +        <HdOutlinedButton text={data["footer-contact-us-button"]} onClick={() => router.push("/contact-us")}/>
```suggestion
        <HdOutlinedButton text={data[VARIABLE]} onClick={() => router.push("/contact-us")}/>
```

2022-09-09 21:45 UTC, hrachocode commented on pages/components/workWithUs/WorkWithUs.tsx
> +        <HdOutlinedButton text={data["footer-contact-us-button"]} onClick={() => router.push("/contact-us")}/>
```suggestion
        <HdOutlinedButton text={data["footer-contact-us-button"]} onClick={() => router.push(VARIABLE)}/>
```

2022-09-09 21:45 UTC, hrachocode commented on pages/utils/formatApiPortfolioData.ts
> +  data.reduce((accum: any, product: any) => {
```suggestion
  data.reduce((accum: any, product: any) => {
```

I cannot understand whats going on in this function

1. we should place all the routes into variables(_embedded etc.)
2. we need to split code into multiple parts to make it readable

2022-09-09 21:45 UTC, hrachocode commented on pages/utils/formatApiPortfolioData.ts
> +  data.reduce((accum: any, product: any) => {
3 missing types

2022-09-09 21:45 UTC, hrachocode commented on pages/utils/formatApiPortfolioProduct.ts
> +  data.reduce((accum: any, product: any) => {
same applied here and also

4. I see repeating logic in two separate functions, prolly we can combine them

2022-09-13 07:31 UTC, rafonersisyan commented on pages/case-study/[id].tsx
> +    const fetchData = async () => {
we can't, because fetchData function do different functionality every time, except calling httpClient function inside of it

2022-09-13 07:32 UTC, rafonersisyan commented on pages/case-study/index.tsx
> +// import { BlogCategories } from "../components/blogPage/categories/BlogCategories";
only in this file, it would be changed

2022-09-13 08:21 UTC, rafonersisyan commented on pages/components/portfolioInnerPage/PortfolioInnerPage.tsx
> +export const PortfolioInnerPage = ({ product }: any) => {
product is array, inside of it there is an object which contains 13 values, is it okay to write types for all of them, while i am passing it by props in two levels

2022-09-13 08:24 UTC, rafonersisyan commented on pages/components/shared/Spinner.tsx
> +            <Skeleton sx={{ width: "100%", height: "10vh", margin: 0 }}/>
yes

2022-09-13 08:25 UTC, rafonersisyan commented on pages/components/workWithUs/WorkWithUs.tsx
> +        <HdOutlinedButton text={data["footer-contact-us-button"]} onClick={() => router.push("/contact-us")}/>
it comes from data, as all the strings

2022-09-13 09:17 UTC, hrachocode approved these changes

2022-09-13 09:18 UTC, merged