case study page with backend
hrachocode/hydralab pull request #51
Opened 2022-09-14 12:54 UTC by rafonersisyan

2022-09-14 13:36 UTC, hrachocode requested changes

2022-09-14 13:36 UTC, hrachocode commented on pages/components/relatedContent/RelatedContent.tsx
> +        Related Content
should this come from backend?

2022-09-15 08:35 UTC, rafonersisyan commented on pages/components/relatedContent/RelatedContent.tsx
> +        Related Content
for the inner page we still haven't connected backend texts

2022-09-15 08:47 UTC, hrachocode approved these changes

2022-09-15 09:03 UTC, merged