error handling, keeping in redux
hrachocode/hydralab pull request #62
Opened 2022-09-28 09:58 UTC by rafonersisyan

2022-09-28 10:57 UTC, hrachocode requested changes

2022-09-28 10:57 UTC, hrachocode commented on components/errorPopup/ErrorPopup.tsx
> +  const data = useSelector((state: any) => state.error.error);
```suggestion
  const data = useSelector((state: IRootState) => state.error.error);
```

2022-09-28 10:57 UTC, hrachocode commented on components/errorPopup/ErrorPopup.tsx
> +    setTimeout(() => {
why you need set timeout here?

2022-09-28 10:57 UTC, hrachocode commented on components/errorPopup/errorPopup.slice.ts
> +  initialState: { error: { isError: false } },
```suggestion
  initialState: { 
      isError: false 
  },
```

?

2022-09-28 10:57 UTC, hrachocode commented on components/errorPopup/style.ts
> +  height: "90vh",
will this work for larger screens? you can minimize the screen with `cntrl` + `-`

to check not only responsive, but also larger screens

2022-09-28 10:57 UTC, hrachocode commented on pages/about-us.tsx
>    });
```suggestion
    if(error){
      dispatch(errorHandling({ isError: true }));
    }else {
      dispatch(errorHandling({ isError: false }));
    }
    dispatch(changeData(texts));
  });
```

create a separate hook called useFetchedData(error, data) and move all this logic there and use overall in project.

2022-09-28 10:57 UTC, hrachocode commented on pages/join-us.tsx
> +        error: error?.data.message
```suggestion
        error: error?.data?.message
```

same everywhere

2022-09-29 13:13 UTC, rafonersisyan commented on pages/about-us.tsx
>    });
i can't use custom hooks in useEffect

2022-09-29 13:13 UTC, rafonersisyan commented on components/errorPopup/style.ts
> +  height: "90vh",
yes

2022-09-29 13:13 UTC, rafonersisyan commented on components/errorPopup/ErrorPopup.tsx
> +    setTimeout(() => {
removed

2022-09-30 13:59 UTC, hrachocode approved these changes

2022-09-30 14:00 UTC, merged